/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBody: typeof import('./src/components/layout/AppBody.vue')['default']
    AppCarousel: typeof import('./src/components/ui/AppCarousel.vue')['default']
    AppHeader: typeof import('./src/components/layout/AppHeader.vue')['default']
    AppListApplication: typeof import('./src/components/subComponents/AppListApplication.vue')['default']
    AppMain: typeof import('./src/components/AppMain.vue')['default']
    AppSearch: typeof import('./src/components/ui/AppSearch.vue')['default']
    AppTitle: typeof import('./src/components/ui/AppTitle.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElRow: typeof import('element-plus/es')['ElRow']
  }
}
